defaults:
  - base_ippo

name: ippo
learning_rate: 0.0003
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef_mode: adaptive
ent_coef: 0.1
ent_coef_end: 0.01
target_entropy_frac: 0.6
ent_coef_lr: 0.003
ent_coef_min: 0.001
ent_coef_max: 0.5
vf_coef: 0.5
vf_clip: 10.0
n_steps: 512
batch_size: 128
update_epochs: 2
hidden_size: 256
max_grad_norm: 0.5
normalize_obs: true
flatten_obs: false
device: auto
