defaults:
  - base_logging

log_dir: logs
run_name: null
log_interval: 1
video_enabled: true
video_every_n_episodes: 100
video_max_steps: 600
video_fps: 10
video_keep_frames: false
log_agent_episode_details: true
